name: Count Severity

on:
  workflow_dispatch:
    inputs:
      file_name:
        description: 'Enter the json file '
        required: true

jobs:
  user-input:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Custom Script
        run: |
          # Access the input parameter value using ${{ github.event.inputs.file_name }}
          file_name="${{ github.event.inputs.file_name }}"
          echo "User input: $file_name"
          # Use $file_name in your script
          chmod +x count_severity.sh
          ./count_severity.sh "$file_name" > result.json
          
      - name: Format and Display Table
        run: |
          echo "user-input summary"
          echo "::set-output name=table::\`\`\`json\n$(cat result.json)\n\`\`\`"

      - name: Display Table in Job Summary
        run: |
          echo "${{ steps.Format.outputs.table }}"
