name: Count Severity

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      file_name:
        description: 'Enter the json file '
        required: true

jobs:
  count_severity:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Custom Script
        run: |
          file_name="${{ github.event.inputs.file_name }}"
          echo "User input: $file_name"
          chmod +x count_severity.sh
          ./count_severity.sh "$file_name" > result.json
          cat result.json

      - name: Generate HTML Summary
        if: always()
        uses: actions/github-script@v4
        with:
         github-token: ${{ secrets.GITHUB_TOKEN }}

         script: |
           const fs = require('fs');
           const path = require('path');

            // Create HTML content
            const htmlContent = `   
              <html>
               <body>
                  <table border='1'>
               <thead>
                <tr>
                  <th>Severity</th>
                  <th>Count</th>
                </tr>
              </thead>
              <tbody>
                ${fs.readFileSync('result.json').toString()
                  |> JSON.parse
                  |> (data) =>
                    data.SeverityCount
                      |> (severityCount) =>
                        severityCount
                          .map(
                            ({ severity, count }) =>
                              `<tr><td>${severity}</td><td>${count}</td></tr>`
                          )
                          .join('')}
              </tbody>
            </table>
            <p>Trafficlight: ${fs.readFileSync('result.json').toString() |> JSON.parse |> (data) => data.Trafficlight}</p>
             </body>
             </html>
             `;

              // Write the HTML content to summary.html
            fs.writeFileSync(path.join(process.env.GITHUB_WORKSPACE, 'summary.html'), htmlContent);


      - name: Display
        run: cat $GITHUB_WORKSPACE/summary.html >> $GITHUB_STEP_SUMMARY
